#!/bin/bash

NAME="Daredevil Dashboard"
DAEMON=/usr/bin/node
ARGS="/home/admin/index.js"
USER=admin
PIDFILE=/var/run/daredash.pid

do_start() {
	/sbin/start-stop-daemon --start --exec $DAEMON $ARGS --pidfile $PIDFILE --make-pidfile --background --chuid $USER 
}

do_stop() {
	/sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
}

case "$1" in
    start)
        echo "Starting $NAME"
        do_start
        ;;
    stop)
        echo "Stopping $NAME"
        do_stop
        ;;
    restart)
        echo "Restarting $NAME"
        do_stop
        do_start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
 esac

 exit 0